"""init

Revision ID: 5f28b409bb47
Revises: 
Create Date: 2025-12-09 00:28:16.700495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f28b409bb47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('to_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_requests_from_telegram_id'), 'connection_requests', ['from_telegram_id'], unique=False)
    op.create_index(op.f('ix_connection_requests_project_id'), 'connection_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_connection_requests_to_telegram_id'), 'connection_requests', ['to_telegram_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('avatar_file_id', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('stack', sa.String(length=256), nullable=True),
    sa.Column('framework', sa.String(length=128), nullable=True),
    sa.Column('skills', sa.String(length=256), nullable=True),
    sa.Column('goals', sa.String(length=256), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_telegram_id'), 'profiles', ['telegram_id'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('stack', sa.String(length=256), nullable=True),
    sa.Column('idea', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('needs_now', sa.Text(), nullable=True),
    sa.Column('looking_for_role', sa.String(length=256), nullable=True),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('extra', sa.String(length=256), nullable=True),
    sa.Column('team_limit', sa.Integer(), nullable=True),
    sa.Column('current_members', sa.Integer(), nullable=False),
    sa.Column('chat_link', sa.String(length=256), nullable=True),
    sa.Column('image_file_id', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_telegram_id'), 'projects', ['owner_telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_owner_telegram_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_profiles_telegram_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_connection_requests_to_telegram_id'), table_name='connection_requests')
    op.drop_index(op.f('ix_connection_requests_project_id'), table_name='connection_requests')
    op.drop_index(op.f('ix_connection_requests_from_telegram_id'), table_name='connection_requests')
    op.drop_table('connection_requests')
    # ### end Alembic commands ###
